wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709945852.529155
    t:
      1:
      - 1
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
kernel:
  desc: null
  value: rbf
C:
  desc: null
  value: 44.86523681314139
epsilon:
  desc: null
  value: 0.014196476308818446
tol:
  desc: null
  value: 5.2953730854031765e-06
gamma:
  desc: null
  value: 0.9044390311282856
